name: Build and publish Docker distributions to Github Container Registry ghcr.io

on:
  push:
    branches:
      - master
      - version-*
    # paths:
    #   - gradle.properties


jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - run: echo "::set-output name=REPOSITORY_NAME::$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')"
      id: meta
    - name: Read version from gradle.properties
      id: release_version
      uses: christian-draeger/read-properties@1.0.1
      with:
        path: ./gradle.properties
        property: release_version
<<<<<<< Updated upstream
=======
    - name: Echo release version
      run: echo ghcr.io/${{ github.repository }}:${{ steps.release_version.outputs.value }}
>>>>>>> Stashed changes
    - name: log in to github container registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
<<<<<<< Updated upstream
        build-args: |
          tags: ghcr.io/${{ github.repository }}:${{ steps.version.outputs.prop }}
          labels: com.exactpro.th2.${{ steps.repo.outputs.REPOSITORY_NAME }}=${{ steps.version.outputs.prop }}
=======
        tags: ghcr.io/${{ github.repository }}:${{ steps.release_version.outputs.value }}
        labels: com.exactpro.th2.${{ steps.repo.outputs.REPOSITORY_NAME }}=${{ steps.version.outputs.prop }}

>>>>>>> Stashed changes
